### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by hajime725** [yuhei1horibe/Zedboard_audio_driver#1]
SND_SOC_DAILINK_DEFS and other define is not found in petalinux project.
I use petalinux-2019.2.

build log is here ↓

[INFO] building project
[INFO] sourcing bitbake
[INFO] generating user layers
[INFO] generating workspace directory
INFO: bitbake petalinux-user-image
Loading cache: 100% |##############################################################################################| Time: 0:00:00
Loaded 3978 entries from dependency cache.
Parsing recipes: 100% |############################################################################################| Time: 0:00:12
Parsing of 2893 .bb files complete (2891 cached, 2 parsed). 3980 targets, 169 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
WARNING: /opt/pkg/petalinux/components/yocto/source/arm/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx_2019.2.bb.do_compile is tainted from a forced run
Initialising tasks: 100% |#########################################################################################| Time: 0:00:05
Checking sstate mirror object availability: 100% |#################################################################| Time: 0:00:11
Sstate summary: Wanted 134 Found 9 Missed 250 Current 866 (6% match, 87% complete)
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
NOTE: linux-xlnx: compiling from external source tree /home/hajime/FPGA/testproj/testproject/components/plnx_workspace/sources/linux-xlnx
ERROR: linux-xlnx-4.19-xilinx-v2019.2+git999-r0 do_compile: oe_runmake failed
ERROR: linux-xlnx-4.19-xilinx-v2019.2+git999-r0 do_compile: Function failed: do_compile (log file is located at /home/hajime/FPGA/testproj/testproject/build/tmp/work/plnx_zynq7-xilinx-linux-gnueabi/linux-xlnx/4.19-xilinx-v2019.2+git999-r0/temp/log.do_compile.24621)
ERROR: Logfile of failure stored in: /home/hajime/FPGA/testproj/testproject/build/tmp/work/plnx_zynq7-xilinx-linux-gnueabi/linux-xlnx/4.19-xilinx-v2019.2+git999-r0/temp/log.do_compile.24621
Log data follows:
| DEBUG: Executing python function externalsrc_compile_prefunc
| NOTE: linux-xlnx: compiling from external source tree /home/hajime/FPGA/testproj/testproject/components/plnx_workspace/sources/linux-xlnx
| DEBUG: Python function externalsrc_compile_prefunc finished
| DEBUG: Executing shell function do_compile
| NOTE: make -j 4 HOSTCC=gcc  -isystem/home/hajime/FPGA/testproj/testproject/build/tmp/work/plnx_zynq7-xilinx-linux-gnueabi/linux-xlnx/4.19-xilinx-v2019.2+git999-r0/recipe-sysroot-native/usr/include -O2 -pipe -L/home/hajime/FPGA/testproj/testproject/build/tmp/work/plnx_zynq7-xilinx-linux-gnueabi/linux-xlnx/4.19-xilinx-v2019.2+git999-r0/recipe-sysroot-native/usr/lib -L/home/hajime/FPGA/testproj/testproject/build/tmp/work/plnx_zynq7-xilinx-linux-gnueabi/linux-xlnx/4.19-xilinx-v2019.2+git999-r0/recipe-sysroot-native/lib -Wl,-rpath-link,/home/hajime/FPGA/testproj/testproject/build/tmp/work/plnx_zynq7-xilinx-linux-gnueabi/linux-xlnx/4.19-xilinx-v2019.2+git999-r0/recipe-sysroot-native/usr/lib -Wl,-rpath-link,/home/hajime/FPGA/testproj/testproject/build/tmp/work/plnx_zynq7-xilinx-linux-gnueabi/linux-xlnx/4.19-xilinx-v2019.2+git999-r0/recipe-sysroot-native/lib -Wl,-rpath,/home/hajime/FPGA/testproj/testproject/build/tmp/work/plnx_zynq7-xilinx-linux-gnueabi/linux-xlnx/4.19-xilinx-v2019.2+git999-r0/recipe-sysroot-native/usr/lib -Wl,-rpath,/home/hajime/FPGA/testproj/testproject/build/tmp/work/plnx_zynq7-xilinx-linux-gnueabi/linux-xlnx/4.19-xilinx-v2019.2+git999-r0/recipe-sysroot-native/lib -Wl,-O1 -Wl,--allow-shlib-undefined -Wl,--dynamic-linker=/home/hajime/FPGA/testproj/testproject/build/tmp/sysroots-uninative/x86_64-linux/lib/ld-linux-x86-64.so.2 HOSTCPP=gcc  -E zImage CC=arm-xilinx-linux-gnueabi-gcc  -mno-thumb-interwork -marm -fuse-ld=bfd -fdebug-prefix-map=/home/hajime/FPGA/testproj/testproject/build/tmp/work/plnx_zynq7-xilinx-linux-gnueabi/linux-xlnx/4.19-xilinx-v2019.2+git999-r0=/usr/src/debug/linux-xlnx/4.19-xilinx-v2019.2+git999-r0 -fdebug-prefix-map=/home/hajime/FPGA/testproj/testproject/build/tmp/work/plnx_zynq7-xilinx-linux-gnueabi/linux-xlnx/4.19-xilinx-v2019.2+git999-r0/recipe-sysroot= -fdebug-prefix-map=/home/hajime/FPGA/testproj/testproject/build/tmp/work/plnx_zynq7-xilinx-linux-gnueabi/linux-xlnx/4.19-xilinx-v2019.2+git999-r0/recipe-sysroot-native=  -fdebug-prefix-map=/home/hajime/FPGA/testproj/testproject/build/tmp/work-shared/plnx-zynq7/kernel-source=/usr/src/kernel   LD=arm-xilinx-linux-gnueabi-ld.bfd   UIMAGE_LOADADDR=0x8000
|   GEN     ./Makefile
|   Using /home/hajime/FPGA/testproj/testproject/components/plnx_workspace/sources/linux-xlnx as source for kernel
|   CALL    /home/hajime/FPGA/testproj/testproject/components/plnx_workspace/sources/linux-xlnx/scripts/checksyscalls.sh
|   CHK     include/generated/compile.h
|   CC      sound/soc/zedboard/zed_pl_snd_card.o
| /home/hajime/FPGA/testproj/testproject/components/plnx_workspace/sources/linux-xlnx/sound/soc/zedboard/zed_pl_snd_card.c:150:32: error: expected ')' before '(' token
|               DAILINK_COMP_ARRAY(COMP_CPU("xlnx_i2s_capture")),
|                                 ^
|                                 )
| /home/hajime/FPGA/testproj/testproject/components/plnx_workspace/sources/linux-xlnx/sound/soc/zedboard/zed_pl_snd_card.c:155:32: error: expected ')' before '(' token
|               DAILINK_COMP_ARRAY(COMP_CPU("xlnx_i2s_playback")),
|                                 ^
|                                 )
| /home/hajime/FPGA/testproj/testproject/components/plnx_workspace/sources/linux-xlnx/sound/soc/zedboard/zed_pl_snd_card.c:163:9: error: implicit declaration of function 'SND_SOC_DAILINK_REG'; did you mean 'SND_SOC_DAPM_REG'? [-Werror=implicit-function-declaration]
|          SND_SOC_DAILINK_REG(xlnx_i2s_playback),
|          ^~~~~~~~~~~~~~~~~~~
|          SND_SOC_DAPM_REG
| /home/hajime/FPGA/testproj/testproject/components/plnx_workspace/sources/linux-xlnx/sound/soc/zedboard/zed_pl_snd_card.c:163:29: error: 'xlnx_i2s_playback' undeclared here (not in a function)
|          SND_SOC_DAILINK_REG(xlnx_i2s_playback),
|                              ^~~~~~~~~~~~~~~~~
| /home/hajime/FPGA/testproj/testproject/components/plnx_workspace/sources/linux-xlnx/sound/soc/zedboard/zed_pl_snd_card.c:169:29: error: 'xlnx_i2s_capture' undeclared here (not in a function)
|          SND_SOC_DAILINK_REG(xlnx_i2s_capture),
|                              ^~~~~~~~~~~~~~~~
| /home/hajime/FPGA/testproj/testproject/components/plnx_workspace/sources/linux-xlnx/sound/soc/zedboard/zed_pl_snd_card.c: In function 'zed_snd_probe':
| /home/hajime/FPGA/testproj/testproject/components/plnx_workspace/sources/linux-xlnx/sound/soc/zedboard/zed_pl_snd_card.c:264:18: error: 'struct snd_soc_dai_link' has no member named 'platforms'; did you mean 'platform_name'?
|              dai->platforms->of_node = pnode;
|                   ^~~~~~~~~
|                   platform_name
| /home/hajime/FPGA/testproj/testproject/components/plnx_workspace/sources/linux-xlnx/sound/soc/zedboard/zed_pl_snd_card.c:266:18: error: 'struct snd_soc_dai_link' has no member named 'cpus'; did you mean 'ops'?
|              dai->cpus->of_node = node[i];
|                   ^~~~
|                   ops
| cc1: some warnings being treated as errors
| make[5]: *** [/home/hajime/FPGA/testproj/testproject/components/plnx_workspace/sources/linux-xlnx/scripts/Makefile.build:306: sound/soc/zedboard/zed_pl_snd_card.o] Error 1
| make[4]: *** [/home/hajime/FPGA/testproj/testproject/components/plnx_workspace/sources/linux-xlnx/scripts/Makefile.build:546: sound/soc/zedboard] Error 2
| make[3]: *** [/home/hajime/FPGA/testproj/testproject/components/plnx_workspace/sources/linux-xlnx/scripts/Makefile.build:546: sound/soc] Error 2
| make[2]: *** [/home/hajime/FPGA/testproj/testproject/components/plnx_workspace/sources/linux-xlnx/Makefile:1052: sound] Error 2
| make[2]: *** Waiting for unfinished jobs....
| make[1]: *** [Makefile:146: sub-make] Error 2
| make: *** [Makefile:24: __sub-make] Error 2
| ERROR: oe_runmake failed
| WARNING: /home/hajime/FPGA/testproj/testproject/build/tmp/work/plnx_zynq7-xilinx-linux-gnueabi/linux-xlnx/4.19-xilinx-v2019.2+git999-r0/temp/run.do_compile.24621:1 exit 1 from 'exit 1'
| ERROR: Function failed: do_compile (log file is located at /home/hajime/FPGA/testproj/testproject/build/tmp/work/plnx_zynq7-xilinx-linux-gnueabi/linux-xlnx/4.19-xilinx-v2019.2+git999-r0/temp/log.do_compile.24621)
ERROR: Task (/opt/pkg/petalinux/components/yocto/source/arm/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx_2019.2.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3492 tasks of which 3487 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /opt/pkg/petalinux/components/yocto/source/arm/layers/meta-xilinx/meta-xilinx-bsp/recipes-kernel/linux/linux-xlnx_2019.2.bb:do_compile
Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
ERROR: Failed to build project

**Comment by yuhei1horibe** [comment]
PetaLinux tools 2019.2 uses Linux kernel version 4.19 (this can be seen in the log). This module is supposed to be complied with kernel version 5.4 (see the latest Xilinx/linux-xlnx repository below).
https://github.com/Xilinx/linux-xlnx

This driver will never support older kernel version 4.19.
